# Generated by Django 4.0.1 on 2022-01-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Financa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.FloatField()),
                ('renda_extra', models.FloatField()),
                ('gastos_com_aluguel', models.FloatField()),
                ('gastos_com_mercado', models.FloatField()),
                ('gastos_extras', models.FloatField()),
                ('data_de_recebimento', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financas.user')),
            ],
        ),
    ]
