# Generated by Django 4.0.1 on 2022-01-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.user'),
        ),
    ]
